name: LogBack
version: '${project.version}'
description: Login at a fixed location, manually teleport back to the logout location
main: vip.floatationdevice.msu.logback.LogBack
authors: [ MCUmbrella ]
website: https://github.com/MSUPlugins/LogBack
api-version: 1.13
depend:
  - MSUCore
commands:
  logback:
    description: "Teleport to logout location"
    aliases:
      - lback
permissions:
  logback.logback:
    description: "Allows the player to teleport to logout location"
    default: true
  logback.setspawn:
    description: "Allows the player to set the login location"
    default: op
